### ISSUE TITLE
negative multiplier step values

### ISSUE THREAD

**Issue by bjohnso005** [wallaceEcoMod/wallace#335]
In Model component, Wallace(v1.9) crashes if you set the multiplier step value to a negative value, instead of giving a warning message.

**Comment by andrepazv** [comment]
resolved

**Comment by bjohnso005** [comment]
Negative step value crash fixed, but still crashing when step value set to "0"

**Comment by andrepazv** [comment]
Done :)
